hostname: localhost
client:
  service-url:
    defaultZone: http://localhost:8761/eureka

server:
  port: ${PORT}
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: fit.force.email@gmail.com # ${MAIL_USERNAME} # your gmail account
    password: ${MAIL_PASSWORD} # ${MAIL_PASSWORD} # your gmail password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: security
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME} # postgres
    password: ${DB_PASSWORD} # root
  flyway:
    locations: classpath:db/migration
    schemas: security
    enabled: true
    baselineOnMigrate: true
    cleanDisabled: false
    cleanOnValidationError: true
    clean-on-startup: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


#  PORT=9898;DB_HOST=localhost;DB_USERNAME=postgres;DB_NAME=fit_force;DB_PASSWORD=root;EMAIL_PASS=hcyffnroxmrupmzo